// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 056f3e09b7c2ac41d26bb333c45d754b0de3ac2698fc3e7c561206eba88ea461

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "saas-account-v3" | "saas-login-v3";

export const themeNames: ThemeName[] = ["saas-account-v3", "saas-login-v3"];

export type KcEnvName = "MY_APP_API_URL" | "MY_APP_PALETTE";

export const kcEnvNames: KcEnvName[] = ["MY_APP_API_URL", "MY_APP_PALETTE"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    MY_APP_API_URL: "",
    MY_APP_PALETTE: "dracula"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    | import("./account/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));
export const KcAccountPage = lazy(() => import("./account/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                    case "account":
                        return <KcAccountPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}
